Added my name to people.json
greenberrynl/hacktoberfest2019 pull request #21
Opened 2019-10-03 17:21 UTC by SamWolfs

We did it, we did it, we did it yay!

2019-10-03 17:22 UTC, RamonGebben approved these changes

2019-10-03 17:24 UTC, the-mo requested changes

2019-10-03 17:24 UTC, the-mo commented on people.json
> +    "linkedin": "https://github.com/SamWolfs/hacktoberfest2019.git"
This should be a linkedin url.

2019-10-04 05:52 UTC, RamonGebben approved these changes

2019-10-04 05:53 UTC, merged